### ISSUE TITLE
Use mfinder binary. Error occurs like this

### ISSUE THREAD

**Issue by dongxudongxu** [aanastasiou/pymotifcounter#3]
Traceback (most recent call last):
  File "/home/zengdongxu/lab/graphmining/Coupledgraph/test.py", line 22, in <module>
    g_mtf_count = motif_counter(G)
  File "/home/zengdongxu/miniconda3/envs/dongxu/lib/python3.10/site-packages/pymotifcounter/abstractcounter.py", line 338, in __call__
    final_output = self._output_transformer.from_file(self.out_param.value, ctx)
  File "/home/zengdongxu/miniconda3/envs/dongxu/lib/python3.10/site-packages/pymotifcounter/abstractcounter.py", line 52, in from_file
    return self.__call__(str_data, ctx)
  File "/home/zengdongxu/miniconda3/envs/dongxu/lib/python3.10/site-packages/pymotifcounter/counter_mfinder.py", line 51, in __call__
    df_output = pandas.DataFrame(columns=list(parsed_output[0]["enumeration"][0].keys()), index=None)
  File "/home/zengdongxu/miniconda3/envs/dongxu/lib/python3.10/site-packages/pyparsing/results.py", line 193, in __getitem__
    return self._toklist[i]
IndexError: list index out of range

**Comment by aanastasiou** [comment]
Hello @dongxudongxu, thank you for bringing this to my attention, can you please share the code, or a minimal example that would generate this error so that we can see what exactly is going on? 

Looking forward to hearing from you
